// ─────────────────────────────────────────────────────────────────────────────
// TV App Data — Nikhil's curated collection
// ─────────────────────────────────────────────────────────────────────────────

export type WatchStatus =
  | "completed"      // Watched fully
  | "watching"       // Currently in progress
  | "dropped"        // Left in between, didn't enjoy
  | "watchlist";     // Plan to watch

export interface TVShow {
  id: string;
  type: "show";
  title: string;
  year: number;
  endYear?: number;
  genres: string[];
  imdbRating: number;
  myRating?: number;
  seasons: number;
  episodes?: number;
  synopsis: string;
  posterUrl: string;
  posterGradient: string; // fallback
  network?: string;
  status: WatchStatus;
  watchProgress?: string; // e.g. "S3 E6", "Completed S1"
}

export interface Movie {
  id: string;
  type: "movie";
  title: string;
  year: number;
  genres: string[];
  imdbRating: number;
  myRating?: number;
  runtime: number; // minutes
  synopsis: string;
  posterUrl: string;
  posterGradient: string;
  director?: string;
  status: WatchStatus;
}

export type TVItem = TVShow | Movie;

// ─────────────────────────────────────────────────────────────────────────────
// TV SHOWS
// ─────────────────────────────────────────────────────────────────────────────

export const shows: TVShow[] = [
  // ── 10/10 ──────────────────────────────────────────────────────────────────
  {
    id: "succession",
    type: "show",
    title: "Succession",
    year: 2018,
    endYear: 2023,
    genres: ["Drama", "Dark Comedy"],
    imdbRating: 8.9,
    myRating: 10,
    seasons: 4,
    episodes: 39,
    synopsis:
      "The Roy family controls one of the biggest media and entertainment conglomerates in the world. But the patriarch is aging and his four children jockey for position.",
    posterUrl: "https://image.tmdb.org/t/p/w500/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    network: "HBO",
    status: "completed",
    watchProgress: "All 4 seasons",
  },
  {
    id: "modern-family",
    type: "show",
    title: "Modern Family",
    year: 2009,
    endYear: 2020,
    genres: ["Comedy", "Family"],
    imdbRating: 8.5,
    myRating: 10,
    seasons: 11,
    episodes: 250,
    synopsis:
      "Three diverse family branches of the Pritchett-Dunphy-Tucker clan are joined by their ties to the larger family patriarch, Jay Pritchett.",
    posterUrl: "https://image.tmdb.org/t/p/w500/k5Qg5rgPoKdh3yTJJrLtyoyYGwC.jpg",
    posterGradient: "linear-gradient(145deg, #f7971e 0%, #ffd200 50%, #e67e22 100%)",
    network: "ABC",
    status: "completed",
    watchProgress: "All 11 seasons",
  },
  {
    id: "agents-of-shield",
    type: "show",
    title: "Agents of S.H.I.E.L.D.",
    year: 2013,
    endYear: 2020,
    genres: ["Action", "Adventure", "Sci-Fi"],
    imdbRating: 7.5,
    myRating: 10,
    seasons: 7,
    episodes: 136,
    synopsis:
      "The missions of the Strategic Homeland Intervention, Enforcement and Logistics Division, a fictional secret agency, led by Agent Phil Coulson.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
    posterGradient: "linear-gradient(145deg, #141e30 0%, #243b55 50%, #1a1a2e 100%)",
    network: "ABC / Marvel",
    status: "completed",
    watchProgress: "All 7 seasons",
  },
  {
    id: "mumbai-diaries",
    type: "show",
    title: "Mumbai Diaries",
    year: 2021,
    genres: ["Drama", "Medical", "Thriller"],
    imdbRating: 8.3,
    myRating: 10,
    seasons: 2,
    episodes: 16,
    synopsis:
      "Set against the backdrop of the 2008 Mumbai terror attacks, the show follows a group of medical professionals at a government hospital during a crisis.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jDZXjtO3i1WpePWmg7paVKNpdfz.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a2e 0%, #8b0000 50%, #2c0000 100%)",
    network: "Amazon Prime",
    status: "completed",
    watchProgress: "Both seasons",
  },
  {
    id: "the-freelancer",
    type: "show",
    title: "The Freelancer",
    year: 2023,
    genres: ["Action", "Thriller"],
    imdbRating: 7.5,
    myRating: 10,
    seasons: 1,
    episodes: 8,
    synopsis:
      "An ex-cop turned freelancer accepts an assignment to rescue a woman who is held hostage by a dreaded warlord in a war-torn country.",
    posterUrl: "https://image.tmdb.org/t/p/w500/jsGicZboSpbkygvqdfqfbEUSFU3.jpg",
    posterGradient: "linear-gradient(145deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    network: "Amazon Prime",
    status: "completed",
  },
  {
    id: "the-family-man",
    type: "show",
    title: "The Family Man",
    year: 2019,
    genres: ["Action", "Thriller", "Drama"],
    imdbRating: 8.7,
    myRating: 10,
    seasons: 2,
    episodes: 19,
    synopsis:
      "A middle-class man works as an intelligence officer for a government agency while also trying to be a good husband and father.",
    posterUrl: "https://image.tmdb.org/t/p/w500/tE1NUJqw9gV6AVjQ1GTK78LbWJ9.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a1a 0%, #2d3a1a 50%, #1a2d1a 100%)",
    network: "Amazon Prime",
    status: "completed",
    watchProgress: "Both seasons",
  },
  {
    id: "paatal-lok",
    type: "show",
    title: "Paatal Lok",
    year: 2020,
    genres: ["Crime", "Thriller", "Drama"],
    imdbRating: 8.1,
    myRating: 10,
    seasons: 2,
    episodes: 19,
    synopsis:
      "An ambitious case lands on the table of a low-level cop, leading him deep into the criminal underbelly of Delhi.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qL8f1E0W42CFHG8NtpyJFMPeKnw.jpg",
    posterGradient: "linear-gradient(145deg, #0d0d0d 0%, #1a0a00 50%, #2d1500 100%)",
    network: "Amazon Prime",
    status: "completed",
    watchProgress: "Both seasons",
  },
  {
    id: "kaala-paani",
    type: "show",
    title: "Kaala Paani",
    year: 2023,
    genres: ["Thriller", "Drama", "Survival"],
    imdbRating: 8.1,
    myRating: 10,
    seasons: 1,
    episodes: 7,
    synopsis:
      "A mysterious disease spreads across the Andaman and Nicobar Islands, and a doctor races against time to stop the outbreak while a lockdown traps people on the islands.",
    posterUrl: "https://image.tmdb.org/t/p/w500/wQJFHysapAr1eXB5BWNSRbfgTbU.jpg",
    posterGradient: "linear-gradient(145deg, #001f3f 0%, #003d7a 50%, #001a33 100%)",
    network: "Netflix",
    status: "completed",
  },
  {
    id: "game-of-thrones",
    type: "show",
    title: "Game of Thrones",
    year: 2011,
    endYear: 2019,
    genres: ["Fantasy", "Drama", "Adventure"],
    imdbRating: 9.2,
    myRating: 9.5,
    seasons: 8,
    episodes: 73,
    synopsis:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for thousands of years.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a00 0%, #3d1f00 50%, #0a0a0a 100%)",
    network: "HBO",
    status: "completed",
    watchProgress: "All 8 seasons",
  },
  {
    id: "lost",
    type: "show",
    title: "Lost",
    year: 2004,
    endYear: 2010,
    genres: ["Drama", "Mystery", "Sci-Fi"],
    imdbRating: 8.3,
    myRating: 9,
    seasons: 6,
    episodes: 121,
    synopsis:
      "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island. Soon they discover it harbors a number of mysteries.",
    posterUrl: "https://image.tmdb.org/t/p/w500/og6S0aTZU6YUJAbqxeKjCa3kY1E.jpg",
    posterGradient: "linear-gradient(145deg, #1a2f1a 0%, #0d1f0d 50%, #1a1a2e 100%)",
    network: "ABC",
    status: "completed",
    watchProgress: "All 6 seasons",
  },
  {
    id: "from",
    type: "show",
    title: "FROM",
    year: 2022,
    genres: ["Horror", "Mystery", "Sci-Fi"],
    imdbRating: 7.8,
    myRating: 7.5,
    seasons: 3,
    episodes: 31,
    synopsis:
      "Unravels the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep order and search for a way out, they must also survive the threats of the surrounding forest.",
    posterUrl: "https://image.tmdb.org/t/p/w500/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg",
    posterGradient: "linear-gradient(145deg, #0d0d0d 0%, #1a0a00 50%, #3d1a00 100%)",
    network: "MGM+",
    status: "watching",
    watchProgress: "S3 E4",
  },
  {
    id: "yellowjackets",
    type: "show",
    title: "Yellowjackets",
    year: 2021,
    genres: ["Drama", "Mystery", "Thriller"],
    imdbRating: 7.8,
    myRating: 8,
    seasons: 3,
    episodes: 30,
    synopsis:
      "A team of high school girls soccer players survives a plane crash deep in the remote northern wilderness and must endure 19 months of brutal survival, while in the present day the survivors keep dark secrets.",
    posterUrl: "https://image.tmdb.org/t/p/w500/xRnGrn7Z7SC0KIBodocoU1QgDZF.jpg",
    posterGradient: "linear-gradient(145deg, #2d1a00 0%, #1a0d00 50%, #3d2200 100%)",
    network: "Showtime",
    status: "watching",
    watchProgress: "S2 E3",
  },
  {
    id: "him-ym",
    type: "show",
    title: "How I Met Your Mother",
    year: 2005,
    endYear: 2014,
    genres: ["Comedy", "Romance"],
    imdbRating: 8.3,
    myRating: 7.8,
    seasons: 9,
    episodes: 208,
    synopsis:
      "A father recounts to his children the journey of how he met their mother through his social group of friends in New York City.",
    posterUrl: "https://image.tmdb.org/t/p/w500/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    network: "CBS",
    status: "watching",
    watchProgress: "S6 E12",
  },
  {
    id: "the-americans",
    type: "show",
    title: "The Americans",
    year: 2013,
    endYear: 2018,
    genres: ["Drama", "Thriller", "Spy"],
    imdbRating: 8.4,
    myRating: 8.8,
    seasons: 6,
    episodes: 75,
    synopsis:
      "Two Soviet intelligence agents pose as a married couple in Washington, D.C. during the Cold War, while an FBI agent moves in next door.",
    posterUrl: "https://image.tmdb.org/t/p/w500/w1UBlxEXhbKe8sp0fxFZh7MqTce.jpg",
    posterGradient: "linear-gradient(145deg, #1c1c1c 0%, #2d2d2d 50%, #1a1a1a 100%)",
    network: "FX",
    status: "watching",
    watchProgress: "S4 E6",
  },
  {
    id: "special-ops",
    type: "show",
    title: "Special Ops",
    year: 2020,
    genres: ["Action", "Thriller", "Spy"],
    imdbRating: 8.2,
    myRating: 9,
    seasons: 1,
    episodes: 5,
    synopsis:
      "A look into the years-long journey of Himmat Singh, an Indian intelligence officer who believes all the major terrorist attacks are linked to a single entity.",
    posterUrl: "https://image.tmdb.org/t/p/w500/rTOGcNzVMYGezpx9AxX7ilzLNEp.jpg",
    posterGradient: "linear-gradient(145deg, #141414 0%, #1a2d1a 50%, #0d1a0d 100%)",
    network: "Disney+ Hotstar",
    status: "completed",
  },
  {
    id: "the-walking-dead",
    type: "show",
    title: "The Walking Dead",
    year: 2010,
    endYear: 2022,
    genres: ["Horror", "Drama", "Post-Apocalyptic"],
    imdbRating: 8.2,
    myRating: 8.5,
    seasons: 11,
    episodes: 177,
    synopsis:
      "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ng3cMtxYKt1OSQYqFlnKWnVsqNO.jpg",
    posterGradient: "linear-gradient(145deg, #0d0d0d 0%, #1a1a1a 50%, #2d2d2d 100%)",
    network: "AMC",
    status: "completed",
    watchProgress: "All 11 seasons",
  },
  {
    id: "alice-in-borderland",
    type: "show",
    title: "Alice in Borderland",
    year: 2020,
    genres: ["Sci-Fi", "Thriller", "Survival"],
    imdbRating: 7.7,
    myRating: 9,
    seasons: 2,
    episodes: 16,
    synopsis:
      "An avid video-gamer finds himself in a parallel Tokyo where he must compete in dangerous games in order to survive.",
    posterUrl: "https://image.tmdb.org/t/p/w500/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a1a 0%, #1a0a2d 50%, #0f0f1f 100%)",
    network: "Netflix",
    status: "completed",
    watchProgress: "Both seasons",
  },
  {
    id: "dark",
    type: "show",
    title: "Dark",
    year: 2017,
    endYear: 2020,
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    imdbRating: 8.7,
    myRating: 8.2,
    seasons: 3,
    episodes: 26,
    synopsis:
      "A family saga with a supernatural twist set in a German town where the disappearance of two young children exposes the relationships among four families.",
    posterUrl: "https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a0a 0%, #1a1a3d 50%, #0d0d1a 100%)",
    network: "Netflix",
    status: "completed",
    watchProgress: "All 3 seasons",
  },
  {
    id: "you",
    type: "show",
    title: "You",
    year: 2018,
    genres: ["Thriller", "Drama", "Crime"],
    imdbRating: 7.7,
    myRating: 8.8,
    seasons: 5,
    episodes: 49,
    synopsis:
      "A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is fixated on.",
    posterUrl: "https://image.tmdb.org/t/p/w500/oANi0vEE92nuijiZQgPZ88FSxqQ.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a00 0%, #2d1a00 50%, #1a1500 100%)",
    network: "Netflix",
    status: "completed",
    watchProgress: "All 5 seasons",
  },
  {
    id: "tehran",
    type: "show",
    title: "Tehran",
    year: 2020,
    genres: ["Thriller", "Spy", "Drama"],
    imdbRating: 7.5,
    myRating: 9,
    seasons: 2,
    episodes: 16,
    synopsis:
      "A Mossad agent goes undercover in Tehran on a mission that threatens to endanger her life and those around her.",
    posterUrl: "https://image.tmdb.org/t/p/w500/2KWsTNaKpzxuxUnRFU3cZ1WleQC.jpg",
    posterGradient: "linear-gradient(145deg, #1a1400 0%, #2d2200 50%, #1a0a00 100%)",
    network: "Apple TV+",
    status: "completed",
    watchProgress: "Both seasons",
  },
  {
    id: "the-100",
    type: "show",
    title: "The 100",
    year: 2014,
    endYear: 2020,
    genres: ["Sci-Fi", "Drama", "Post-Apocalyptic"],
    imdbRating: 7.7,
    myRating: 9,
    seasons: 7,
    episodes: 100,
    synopsis:
      "Set 97 years after a nuclear war destroyed civilization, when a spaceship housing humanity's lone survivors sends 100 juvenile delinquents back to Earth.",
    posterUrl: "https://image.tmdb.org/t/p/w500/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
    posterGradient: "linear-gradient(145deg, #0a1a0a 0%, #1a2d0a 50%, #0d1f0d 100%)",
    network: "The CW",
    status: "completed",
    watchProgress: "All 7 seasons",
  },

  // ── Dropped ──────────────────────────────────────────────────────────────────
  {
    id: "manifest",
    type: "show",
    title: "Manifest",
    year: 2018,
    endYear: 2023,
    genres: ["Drama", "Mystery", "Thriller"],
    imdbRating: 7.2,
    seasons: 4,
    synopsis: "Flight 828 passengers return after 5 years to discover the world has moved on without them, while struggling with mysterious visions.",
    posterUrl: "https://image.tmdb.org/t/p/w500/eTemCphrglLKrXOsNRhYezHA7H9.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    network: "NBC / Netflix",
    status: "dropped",
    watchProgress: "S2",
  },
  {
    id: "snowpiercer",
    type: "show",
    title: "Snowpiercer",
    year: 2020,
    endYear: 2023,
    genres: ["Sci-Fi", "Drama", "Dystopian"],
    imdbRating: 7.1,
    seasons: 4,
    synopsis: "Set more than seven years after the world has become a frozen wasteland, it follows the remnants of humanity aboard the Snowpiercer.",
    posterUrl: "https://image.tmdb.org/t/p/w500/exKzfiKzMdQBHrdd7zNmKauJkbg.jpg",
    posterGradient: "linear-gradient(145deg, #e0e0e0 0%, #a0a0a0 50%, #606060 100%)",
    network: "TNT",
    status: "dropped",
    watchProgress: "S1",
  },
  {
    id: "breaking-bad",
    type: "show",
    title: "Breaking Bad",
    year: 2008,
    endYear: 2013,
    genres: ["Drama", "Crime", "Thriller"],
    imdbRating: 9.5,
    seasons: 5,
    synopsis: "A chemistry teacher diagnosed with terminal cancer teams with a former student to secure his family's future by manufacturing methamphetamine.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    posterGradient: "linear-gradient(145deg, #1a1400 0%, #2d2200 50%, #1a1a1a 100%)",
    network: "AMC",
    status: "dropped",
    watchProgress: "S1 E4",
  },
  {
    id: "homeland",
    type: "show",
    title: "Homeland",
    year: 2011,
    endYear: 2020,
    genres: ["Drama", "Thriller", "Spy"],
    imdbRating: 8.2,
    seasons: 8,
    synopsis: "A bipolar CIA operative becomes convinced that a recently rescued prisoner of war has been turned by al-Qaeda and is planning a terrorist attack.",
    posterUrl: "https://image.tmdb.org/t/p/w500/6GAvS2e6VIRsms9FpVt33PsCoEW.jpg",
    posterGradient: "linear-gradient(145deg, #141e30 0%, #243b55 50%, #1a1a2e 100%)",
    network: "Showtime",
    status: "dropped",
    watchProgress: "S2",
  },
  {
    id: "veep",
    type: "show",
    title: "Veep",
    year: 2012,
    endYear: 2019,
    genres: ["Comedy", "Political Satire"],
    imdbRating: 8.3,
    seasons: 7,
    synopsis: "Former Senator Selina Meyer finds that being Vice President of the United States is nothing like she expected and everything everyone warned her about.",
    posterUrl: "https://image.tmdb.org/t/p/w500/cdd78fGdaA3EbK2ToZRWcaaB1fx.jpg",
    posterGradient: "linear-gradient(145deg, #1a2d1a 0%, #0d1f0d 50%, #1a1a2e 100%)",
    network: "HBO",
    status: "dropped",
    watchProgress: "S1",
  },
  {
    id: "umbrella-academy",
    type: "show",
    title: "The Umbrella Academy",
    year: 2019,
    endYear: 2023,
    genres: ["Sci-Fi", "Superhero", "Action"],
    imdbRating: 7.9,
    seasons: 4,
    synopsis: "A family of former child heroes, now grown apart, must reunite to continue to protect the world.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qhcwrnnCnN8NE1N6XXKHFmveJR9.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a2d 0%, #2d1a00 50%, #0a0a1a 100%)",
    network: "Netflix",
    status: "dropped",
    watchProgress: "S2",
  },
  {
    id: "the-colony",
    type: "show",
    title: "Colony",
    year: 2016,
    endYear: 2018,
    genres: ["Sci-Fi", "Drama", "Dystopian"],
    imdbRating: 7.4,
    seasons: 3,
    synopsis: "Set in the near future, Colony centers on a family who must make difficult decisions as they balance staying together while being forced to collaborate with a mysterious alien occupation.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qfS0mp22XfTig2EK3jWKiyx7kNy.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a1a 0%, #2d2d1a 50%, #1a2d1a 100%)",
    network: "USA Network",
    status: "dropped",
    watchProgress: "S1",
  },
  {
    id: "chernobyl",
    type: "show",
    title: "Chernobyl",
    year: 2019,
    genres: ["Drama", "Historical", "Thriller"],
    imdbRating: 9.4,
    seasons: 1,
    episodes: 5,
    synopsis: "In April 1986, an explosion at the Chernobyl nuclear power plant in the USSR becomes one of the world's worst man-made catastrophes.",
    posterUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    posterGradient: "linear-gradient(145deg, #2d2d2d 0%, #1a1a1a 50%, #0d0d0d 100%)",
    network: "HBO",
    status: "dropped",
    watchProgress: "E2",
  },
  {
    id: "the-leftovers",
    type: "show",
    title: "The Leftovers",
    year: 2014,
    endYear: 2017,
    genres: ["Drama", "Mystery", "Thriller"],
    imdbRating: 8.3,
    seasons: 3,
    synopsis: "A local police chief, his family and other residents of a small town struggle to adjust to a world where 2% of the world's population has suddenly vanished.",
    posterUrl: "https://image.tmdb.org/t/p/w500/ri8xr223xBb2TeHX3GKypvQPV2B.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a2e 0%, #16213e 50%, #0d0d1a 100%)",
    network: "HBO",
    status: "dropped",
    watchProgress: "S1",
  },
  {
    id: "three-percent",
    type: "show",
    title: "3%",
    year: 2016,
    endYear: 2020,
    genres: ["Sci-Fi", "Drama", "Dystopian"],
    imdbRating: 7.4,
    seasons: 4,
    synopsis: "In a future where the elite inhabit an island paradise far from the crowded slums, you get one chance to join the privileged 3%.",
    posterUrl: "https://image.tmdb.org/t/p/w500/uLBJSLuAQ8UqLIKZVWG3uNEXwjt.jpg",
    posterGradient: "linear-gradient(145deg, #1a1400 0%, #2d2200 50%, #1a1a00 100%)",
    network: "Netflix",
    status: "dropped",
    watchProgress: "S1",
  },
  {
    id: "the-expanse",
    type: "show",
    title: "The Expanse",
    year: 2015,
    endYear: 2022,
    genres: ["Sci-Fi", "Drama", "Thriller"],
    imdbRating: 8.5,
    seasons: 6,
    synopsis: "A thriller set two hundred years in the future, following the case of a missing young woman who leads to the discovery of a vast conspiracy threatening Earth's survival.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8djpxDeWpINnGhjpFXQjnBe6zbx.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a1a 0%, #1a1a3d 50%, #0d0d2d 100%)",
    network: "Amazon Prime",
    status: "dropped",
    watchProgress: "S2",
  },
  {
    id: "battlestar-galactica",
    type: "show",
    title: "Battlestar Galactica",
    year: 2004,
    endYear: 2009,
    genres: ["Sci-Fi", "Drama", "Military"],
    imdbRating: 8.7,
    seasons: 4,
    synopsis: "When the Cylons launch a devastating attack on the Colonies, the few remaining Battlestar ships lead what's left of humanity on a search for a new home.",
    posterUrl: "https://image.tmdb.org/t/p/w500/99PJSbcO2LeM10uOGWeFihNp77j.jpg",
    posterGradient: "linear-gradient(145deg, #141e30 0%, #243b55 50%, #1a1a2e 100%)",
    network: "Sci Fi",
    status: "dropped",
    watchProgress: "S1",
  },

  // ── Watchlist ─────────────────────────────────────────────────────────────────
  {
    id: "brooklyn-99",
    type: "show",
    title: "Brooklyn Nine-Nine",
    year: 2013,
    endYear: 2021,
    genres: ["Comedy", "Crime"],
    imdbRating: 8.4,
    seasons: 8,
    synopsis: "Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD's 99th precinct.",
    posterUrl: "https://image.tmdb.org/t/p/w500/hgRMSOt7a1b8qyQR68vUixJPang.jpg",
    posterGradient: "linear-gradient(145deg, #1a2d3d 0%, #2d4a5f 50%, #1a3d5a 100%)",
    network: "NBC",
    status: "watchlist",
  },
  {
    id: "the-office",
    type: "show",
    title: "The Office",
    year: 2005,
    endYear: 2013,
    genres: ["Comedy", "Mockumentary"],
    imdbRating: 9.0,
    seasons: 9,
    synopsis: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    posterGradient: "linear-gradient(145deg, #1a2d1a 0%, #2d4a2d 50%, #1a3d1a 100%)",
    network: "NBC",
    status: "watchlist",
  },
  {
    id: "silicon-valley",
    type: "show",
    title: "Silicon Valley",
    year: 2014,
    endYear: 2019,
    genres: ["Comedy", "Tech"],
    imdbRating: 8.5,
    seasons: 6,
    synopsis: "In the high-tech gold rush of modern Silicon Valley, the people most qualified to succeed are the least likely to fit in.",
    posterUrl: "https://image.tmdb.org/t/p/w500/4ptpmWBVD9HY9hMh8Cbs6SMiy7p.jpg",
    posterGradient: "linear-gradient(145deg, #1a1a3d 0%, #2d2d5a 50%, #1a1a2e 100%)",
    network: "HBO",
    status: "watchlist",
  },
  {
    id: "suits",
    type: "show",
    title: "Suits",
    year: 2011,
    endYear: 2019,
    genres: ["Drama", "Legal"],
    imdbRating: 8.5,
    seasons: 9,
    synopsis: "A young college drop-out begins working for one of New York City's best lawyers, despite having never attended law school.",
    posterUrl: "https://image.tmdb.org/t/p/w500/vQiryp6LioFxQThywxbC6TuoDjy.jpg",
    posterGradient: "linear-gradient(145deg, #1a1400 0%, #2d2200 50%, #1a1a14 100%)",
    network: "USA Network",
    status: "watchlist",
  },
  {
    id: "ozark",
    type: "show",
    title: "Ozark",
    year: 2017,
    endYear: 2022,
    genres: ["Crime", "Drama", "Thriller"],
    imdbRating: 8.4,
    seasons: 4,
    synopsis: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.",
    posterUrl: "https://image.tmdb.org/t/p/w500/pCGyPVrI9Fzw6rE1Pvi4BIXF6ET.jpg",
    posterGradient: "linear-gradient(145deg, #0a1a1a 0%, #0d2d2d 50%, #0a1a14 100%)",
    network: "Netflix",
    status: "watchlist",
  },
  {
    id: "sopranos",
    type: "show",
    title: "The Sopranos",
    year: 1999,
    endYear: 2007,
    genres: ["Crime", "Drama"],
    imdbRating: 9.2,
    seasons: 6,
    synopsis: "New Jersey mob boss Tony Soprano deals with personal and professional problems in his home and business life that affect his mental state.",
    posterUrl: "https://image.tmdb.org/t/p/w500/rTc7ZXdroqjkKivFPvCPX0Ru7uw.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a00 0%, #2d1a00 50%, #1a1a1a 100%)",
    network: "HBO",
    status: "watchlist",
  },
  {
    id: "24",
    type: "show",
    title: "24",
    year: 2001,
    endYear: 2010,
    genres: ["Action", "Thriller", "Drama"],
    imdbRating: 8.4,
    seasons: 9,
    synopsis: "Counter Terrorist Unit (CTU) agent Jack Bauer has 24 hours to contain a terrorist threat. Each season takes place over 24 real-time hours.",
    posterUrl: "https://image.tmdb.org/t/p/w500/iq6yrZ5LEDXf1ArCOYLq8PIUBpV.jpg",
    posterGradient: "linear-gradient(145deg, #1a0000 0%, #3d0000 50%, #1a0a00 100%)",
    network: "Fox",
    status: "watchlist",
  },
  {
    id: "mr-robot",
    type: "show",
    title: "Mr. Robot",
    year: 2015,
    endYear: 2019,
    genres: ["Thriller", "Drama", "Cyberpunk"],
    imdbRating: 8.6,
    seasons: 4,
    synopsis: "Elliot, a brilliant but highly unstable young cyber-security engineer, is recruited by a mysterious anarchist who goes by the alias 'Mr. Robot'.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kv1nRqgebSsREnd7vdC2pSGjpLo.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a0a 0%, #1a1a1a 50%, #0d0d0d 100%)",
    network: "USA Network",
    status: "watchlist",
  },
  {
    id: "lucifer",
    type: "show",
    title: "Lucifer",
    year: 2016,
    endYear: 2021,
    genres: ["Fantasy", "Comedy", "Crime"],
    imdbRating: 8.1,
    seasons: 6,
    synopsis: "Lucifer Morningstar, bored and unhappy as the Lord of Hell, abandons his throne and retires to Los Angeles, where he helps the LAPD solve murders.",
    posterUrl: "https://image.tmdb.org/t/p/w500/4EYPN5mVIhKLfxGruy7Dy41dTVn.jpg",
    posterGradient: "linear-gradient(145deg, #2d0000 0%, #1a0000 50%, #0d0000 100%)",
    network: "Netflix",
    status: "watchlist",
  },
  {
    id: "dexter",
    type: "show",
    title: "Dexter",
    year: 2006,
    endYear: 2013,
    genres: ["Crime", "Drama", "Thriller"],
    imdbRating: 8.7,
    seasons: 8,
    synopsis: "A forensics expert moonlights as a serial killer of criminals whom he believes have escaped justice.",
    posterUrl: "https://image.tmdb.org/t/p/w500/q8dWfc4JwQuv3HayIZeO84jAXED.jpg",
    posterGradient: "linear-gradient(145deg, #2d0000 0%, #3d1a00 50%, #1a0000 100%)",
    network: "Showtime",
    status: "watchlist",
  },
  {
    id: "psych",
    type: "show",
    title: "Psych",
    year: 2006,
    endYear: 2014,
    genres: ["Comedy", "Crime", "Mystery"],
    imdbRating: 8.3,
    seasons: 8,
    synopsis: "A police consultant with eidetic memory and a knack for hyperactive observation works with the Santa Barbara Police Department as a fake psychic detective.",
    posterUrl: "https://image.tmdb.org/t/p/w500/fDI15gTVbtW5Sbv5QenqecRxWKJ.jpg",
    posterGradient: "linear-gradient(145deg, #1a2d00 0%, #2d4a00 50%, #1a3d00 100%)",
    network: "USA Network",
    status: "watchlist",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// MOVIES
// ─────────────────────────────────────────────────────────────────────────────

export const movies: Movie[] = [
  // ── 10/10 / Favorites ────────────────────────────────────────────────────────
  {
    id: "social-network",
    type: "movie",
    title: "The Social Network",
    year: 2010,
    genres: ["Drama", "Biography"],
    imdbRating: 7.8,
    myRating: 10,
    runtime: 120,
    synopsis: "As Harvard students, Mark Zuckerberg creates Facebook, the social networking site that would connect more than 500 million people, but in the process he is accused of betrayal.",
    posterUrl: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a0a 0%, #1a1a1a 50%, #0d0d2d 100%)",
    director: "David Fincher",
    status: "completed",
  },
  {
    id: "inception",
    type: "movie",
    title: "Inception",
    year: 2010,
    genres: ["Sci-Fi", "Action", "Thriller"],
    imdbRating: 8.8,
    myRating: 10,
    runtime: 148,
    synopsis: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    posterUrl: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a1a 0%, #1a1a3d 50%, #0d0d2d 100%)",
    director: "Christopher Nolan",
    status: "completed",
  },
  {
    id: "iron-man",
    type: "movie",
    title: "Iron Man",
    year: 2008,
    genres: ["Action", "Sci-Fi", "Superhero"],
    imdbRating: 7.9,
    myRating: 10,
    runtime: 126,
    synopsis: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    posterUrl: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    posterGradient: "linear-gradient(145deg, #3d0000 0%, #7a1a00 50%, #3d1a00 100%)",
    director: "Jon Favreau",
    status: "completed",
  },
  {
    id: "wolf-of-wall-street",
    type: "movie",
    title: "The Wolf of Wall Street",
    year: 2013,
    genres: ["Biography", "Crime", "Drama"],
    imdbRating: 8.2,
    myRating: 10,
    runtime: 180,
    synopsis: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
    posterUrl: "https://image.tmdb.org/t/p/w500/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg",
    posterGradient: "linear-gradient(145deg, #1a1400 0%, #2d2200 50%, #3d3000 100%)",
    director: "Martin Scorsese",
    status: "completed",
  },
  {
    id: "bahubali-1",
    type: "movie",
    title: "Baahubali: The Beginning",
    year: 2015,
    genres: ["Action", "Drama", "Fantasy"],
    imdbRating: 8.1,
    myRating: 10,
    runtime: 159,
    synopsis: "In ancient India, an adventurous and daring man becomes involved in a decades-old feud between two warring peoples. He discovers the legend of a great King.",
    posterUrl: "https://image.tmdb.org/t/p/w500/9BAjt8nSSms62uOVYn1t3C3dVto.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a00 0%, #3d2200 50%, #2d1a00 100%)",
    director: "S. S. Rajamouli",
    status: "completed",
  },
  {
    id: "bahubali-2",
    type: "movie",
    title: "Baahubali 2: The Conclusion",
    year: 2017,
    genres: ["Action", "Drama", "Fantasy"],
    imdbRating: 8.2,
    myRating: 10,
    runtime: 167,
    synopsis: "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
    posterUrl: "https://image.tmdb.org/t/p/w500/21sC2assImQIYCEDA84Qh9d1RsK.jpg",
    posterGradient: "linear-gradient(145deg, #2d1a00 0%, #4a3000 50%, #3d2200 100%)",
    director: "S. S. Rajamouli",
    status: "completed",
  },
  {
    id: "avengers-endgame",
    type: "movie",
    title: "Avengers: Endgame",
    year: 2019,
    genres: ["Action", "Sci-Fi", "Superhero"],
    imdbRating: 8.4,
    myRating: 10,
    runtime: 181,
    synopsis: "After the devastating events of Avengers: Infinity War, the universe is in ruins. The Avengers assemble once more in order to reverse Thanos' actions.",
    posterUrl: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a1a 0%, #1a1a3d 50%, #0d0d2d 100%)",
    director: "Russo Brothers",
    status: "completed",
  },
  {
    id: "spiderman-no-way-home",
    type: "movie",
    title: "Spider-Man: No Way Home",
    year: 2021,
    genres: ["Action", "Sci-Fi", "Superhero"],
    imdbRating: 8.2,
    myRating: 10,
    runtime: 148,
    synopsis: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
    posterUrl: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a2d 0%, #2d1a3d 50%, #0a0a1a 100%)",
    director: "Jon Watts",
    status: "completed",
  },
  {
    id: "jurassic-world",
    type: "movie",
    title: "Jurassic World",
    year: 2015,
    genres: ["Action", "Sci-Fi", "Adventure"],
    imdbRating: 7.0,
    myRating: 9,
    runtime: 124,
    synopsis: "A new theme park is built on the original site of Jurassic Park. Everything is going well until the Indominus rex escapes, leaving the island in chaos.",
    posterUrl: "https://image.tmdb.org/t/p/w500/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg",
    posterGradient: "linear-gradient(145deg, #0a1a00 0%, #1a2d00 50%, #1a1a00 100%)",
    director: "Colin Trevorrow",
    status: "completed",
  },
  {
    id: "back-to-the-future",
    type: "movie",
    title: "Back to the Future",
    year: 1985,
    genres: ["Sci-Fi", "Comedy", "Adventure"],
    imdbRating: 8.5,
    myRating: 9,
    runtime: 116,
    synopsis: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend Dr. Emmett Brown.",
    posterUrl: "https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a2d 0%, #2d1a3d 50%, #1a1400 100%)",
    director: "Robert Zemeckis",
    status: "completed",
  },
  {
    id: "the-dark-knight",
    type: "movie",
    title: "The Dark Knight",
    year: 2008,
    genres: ["Action", "Crime", "Drama"],
    imdbRating: 9.0,
    myRating: 10,
    runtime: 152,
    synopsis: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    posterUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a0a 0%, #1a1a1a 50%, #2d0000 100%)",
    director: "Christopher Nolan",
    status: "completed",
  },
  {
    id: "interstellar",
    type: "movie",
    title: "Interstellar",
    year: 2014,
    genres: ["Sci-Fi", "Drama", "Adventure"],
    imdbRating: 8.7,
    myRating: 10,
    runtime: 169,
    synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    posterUrl: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a1a 0%, #1a1a3d 50%, #2d2200 100%)",
    director: "Christopher Nolan",
    status: "completed",
  },
  {
    id: "oppenheimer",
    type: "movie",
    title: "Oppenheimer",
    year: 2023,
    genres: ["Biography", "Drama", "History"],
    imdbRating: 8.3,
    myRating: 9,
    runtime: 180,
    synopsis: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    posterGradient: "linear-gradient(145deg, #1a0a00 0%, #3d2200 50%, #2d1a00 100%)",
    director: "Christopher Nolan",
    status: "completed",
  },
  {
    id: "dune-part-two",
    type: "movie",
    title: "Dune: Part Two",
    year: 2024,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    imdbRating: 8.5,
    myRating: 8.2,
    runtime: 166,
    synopsis: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    posterUrl: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    posterGradient: "linear-gradient(145deg, #2d2200 0%, #3d3000 50%, #1a1400 100%)",
    director: "Denis Villeneuve",
    status: "completed",
  },
  {
    id: "parasite",
    type: "movie",
    title: "Parasite",
    year: 2019,
    genres: ["Drama", "Thriller", "Dark Comedy"],
    imdbRating: 8.5,
    myRating: 8.5,
    runtime: 132,
    synopsis: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    posterUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    posterGradient: "linear-gradient(145deg, #0a0a0a 0%, #1a1a1a 50%, #0d1a0d 100%)",
    director: "Bong Joon-ho",
    status: "completed",
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Lookups
// ─────────────────────────────────────────────────────────────────────────────

export const showById: Record<string, TVShow> = Object.fromEntries(
  shows.map((s) => [s.id, s])
);

export const movieById: Record<string, Movie> = Object.fromEntries(
  movies.map((m) => [m.id, m])
);

export const allItems: TVItem[] = [...shows, ...movies];

export const itemById: Record<string, TVItem> = Object.fromEntries(
  allItems.map((i) => [i.id, i])
);

// ─────────────────────────────────────────────────────────────────────────────
// Curated Home featured picks (4 cards — mirrors music homeFeatured)
// ─────────────────────────────────────────────────────────────────────────────

export interface TVPick {
  itemId: string;
  label: string;
  title: string;
  accent: "A" | "B" | "C" | "D";
}

export const homeFeatured: TVPick[] = [
  { itemId: "modern-family", label: "All-time Favourite", title: "Modern Family", accent: "A" },
  { itemId: "agents-of-shield", label: "Marvel at its Best", title: "Agents of S.H.I.E.L.D.", accent: "B" },
  { itemId: "mumbai-diaries", label: "Best Indian Drama", title: "Mumbai Diaries", accent: "C" },
  { itemId: "social-network", label: "Absolute Classic", title: "The Social Network", accent: "D" },
];

// ─────────────────────────────────────────────────────────────────────────────
// Recently watched (for Home "Recently Watched" row)
// ─────────────────────────────────────────────────────────────────────────────

export const recentlyWatchedIds = [
  "the-americans",
  "yellowjackets",
  "game-of-thrones",
  "from",
  "him-ym",
];
